PharmaTechVe/app

- src/components/Button.tsx
Creation of Button component. I created it to be as adaptable as possible. Let me know if you guys think it's neat
> Creation of Button component

- src/App.tsx
- src/components/RadioButton.tsx
- src/components/Steps.tsx
Added RadioButton and Steps components
- Implemented the **RadioButton** component to allow users to select options.
- Created the **Steps** component to display a step-by-step progress indicator.
Made the steps interactive, allowing users to navigate between steps by tapping on them.
https://github.com/user-attachments/assets/529d81ae-fc5b-4cfb-b519-91457b8d7ef4
https://github.com/user-attachments/assets/62180c58-f55f-4ce2-9c80-e07c11ee65c5
> Features/hu 07/add radiobutton and steps

- src/components/Card-button.tsx
- src/components/CardButton.tsx
> Feature/app 06/cards button to dev

- src/components/Alerts.tsx
Alerts component updated with different types and animations.
> Feature/app 02/alerts to dev

- src/components/DatePickerInput.tsx
- src/components/Input.tsx
- src/components/SearchInput.tsx
Search bar component. It's called SearchInput.tsx in the project tho. It works really good. I'll leave you a video so you can see how it looks.
https://github.com/user-attachments/assets/dd27cd56-8aa3-4b1d-8fd8-9bccaacc5129
I fixed the calendar issue where it chose the previous date.
> Feature/app 5/search bar

- src/components/Checkbox.tsx
Creation of checkbox component. There is not much to say lol. I'll leave a video too
https://github.com/user-attachments/assets/82cd6112-4b1f-4377-98cc-970863624fca
> Feature/app 3/checkbox

- src/components/Popup.tsx
Creation of Popup component. I think it works pretty good. The only thing is that I was wondering if I'd be necessary for the popups to manage svgs too. Right now its only working with images tho. Let me know what you guys think. I think it wouldn't be necessary because the images that it might manage will be small, but idk. 
I'll leave you guys a video too. As I'm usually doing
https://github.com/user-attachments/assets/155e4b42-2e79-4a9d-9e31-ce6ae7169ad6
> Feature/app 10/popup

- src/app/(tabs)/index.tsx
- src/app/login.tsx
- src/app/register.tsx
- src/app/success.tsx
- src/components/Button.tsx
- src/components/Calendar.tsx
- src/components/Checkbox.tsx
- src/components/DatePickerInput.tsx
- src/components/Input.tsx
- src/components/PoppinsText.tsx
- src/components/Popup.tsx
- src/components/SearchInput.tsx
- src/components/Steps.tsx
- src/hooks/usePagination.ts
- src/screens/LoginScreen.tsx
- src/screens/RegisterScreen.tsx
- src/screens/RegistrationSuccessScreen.tsx
- src/screens/tab/BranchesScreen.tsx
- src/screens/tab/CategoriesScreen.tsx
- src/screens/tab/HomeScreen.tsx
- src/screens/tab/OffersScreen.tsx
- src/screens/tab/SupportScreen.tsx
- src/styles/theme.ts
Creation of pagination hook and eliminating the path top comment in all files. I'll leave you guys a video as usual.
https://github.com/user-attachments/assets/49b231f5-87a7-477f-b19f-d484d0c37d93
Escribo en español para que se entienda todo mejor. Como les dije por slack, le había tirado largas a hacer el pagination porque verdaderamente no sabía como manejarlo sin info del backend, pero investigando, vi que es bueno trabajarlo con el componente de react-native FlatList junto con un hook personalizado para la paginación, y es lo que hice en este PR.
Obvio ven en el video como funciona el hook pero todo eso es invetando, emulando un poco como se recibirían los datos desde el backend. Esto lo hice porque necesitaba ver visualmente si verdaderamente estaba funcionando. 
Les dejo el ejemplo …
> Feature/hu 06/pagination

- src/app/(tabs)/_layout.tsx
- src/components/TopBar.tsx
TopBar component. I'll leave you a photo so you see how it looks.
> Feature/app 4/top bar

- src/components/ProgressBar.tsx
> Add ProgressBar component with customizable styles and animations

- package-lock.json
- package.json
- src/app/_layout.tsx
- src/app/cart.tsx
- src/components/Card.tsx
- src/components/CardButton.tsx
- src/components/Carousel.tsx
- src/components/CartTotal.tsx
- src/components/TopBar.tsx
- src/hooks/useCart.ts
- src/redux/slices/cartSlice.ts
- src/redux/store.ts
- src/screens/CartListScreen.tsx
- src/screens/tab/CategoriesScreen.tsx
- src/screens/tab/HomeScreen.tsx
- src/styles/theme.ts
- src/types/Product.ts
PR where I'll be working with the development of the cartlist
> Feature/app m 6/cart list

- src/components/Card.tsx
- src/components/CardButton.tsx
- src/components/Carousel.tsx
- src/screens/tab/HomeScreen.tsx
Home products carousel affordance:
> Fix/app m 3/Home affordance to dev

- package-lock.json
- package.json
- src/lib/sdkConfig.ts
- src/screens/tab/CategoriesScreen.tsx
- src/services/auth.ts
Finally solving the header authorization problem. Que bendición
> Fixing to proper logout

- src/screens/RegistrationSuccessScreen.tsx
- src/screens/tab/CategoriesScreen.tsx
- src/screens/tab/EmailVerificationModal.tsx
- src/screens/tab/HomeScreen.tsx
- src/services/auth.ts
Implementación de la verificación de e-mail.
> Features/app m 7/email verification

- src/app/_layout.tsx
- src/app/index.tsx
- src/app/splash.tsx
- src/screens/SplashScreen.tsx
- src/services/auth.ts
Maintaining user's current session
> Fixing user active session

- package-lock.json
- package.json
- src/app/_layout.tsx
- src/app/loggedInPasswordRecovery.tsx
- src/components/Alerts.tsx
- src/components/TopBar.tsx
- src/lib/sdkConfig.ts
- src/screens/LoggedInPasswordRecoveryScreen.tsx
- src/screens/LoginScreen.tsx
- src/screens/PasswordChangeScreen.tsx
- src/screens/PasswordRecoveryScreen.tsx
- src/screens/RegisterScreen.tsx
- src/screens/tab/EmailVerificationModal.tsx
- src/screens/tab/HomeScreen.tsx
- src/services/auth.ts
Branch where I'll be doing a couple fixes
> General fixes

- app.json
- package-lock.json
- package.json
- src/components/BranchMap.tsx
- src/components/MapViewComponent.tsx
- src/screens/ProductDetailScreen.tsx
- src/screens/tab/BranchesScreen.tsx
PR where I'll be working the google maps integration
> Feature/app i/google maps 1

- src/components/Avatar.tsx
- src/screens/ProfileScreen.tsx
Alerts and profile image fixes
> fix/app f perfil 1/Profile fixes

- src/screens/DirectionChangeScreen.tsx
- src/screens/DirectionCreateScreen.tsx
- src/screens/DirectionScreen.tsx
- src/screens/MenuScreen.tsx
- src/screens/SelectLocationScreen.tsx
Aqui esta el cambio en profile y tambien los de direcciones.
> Fixes in Profile and Directions

- src/app/_layout.tsx
- src/app/categoryDetail/[id].tsx
- src/app/categoryDetail/_layout.tsx
- src/screens/CategoryDetailScreen.tsx
- src/screens/tab/CategoriesScreen.tsx
- src/services/category.ts
> Fix in Categories
